name: ci

on:
  push:
    branches:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: foo-docker-cache-{hash}
          restore-keys: |
            foo-docker-cache-
            
      - name: Build Docker image
        run: docker build -t haseeb/tkxelnginx .

 

      
 

