name: ci

on:
  push:
    branches:
      - "master"
########################################################################################################################################
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: foo-docker-cache-{hash}
          restore-keys: |
            foo-docker-cache-
        
      - name: Check Docker Cache
        id: cache-hit
        run: echo ::set-output name=cache-hit::$(docker pull haseeb:tkxelnginx 2>&1 )
      - name: Check Docker Images
        run: docker images
      - name: Build and Push Docker Image
        if: steps.cache-hit.outputs.cache-hit == '0'
        run: docker build -t haseeb/tkxelnginx .
          

 

      
 

