name: ci

on:
  push:
    branches:
      - "master"
#################################################################################################################################################      
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Docker image
        run: DOCKER_BUILDKIT=1 docker build -t haseeb77777/github --build-arg BUILDKIT_INLINE_CACHE=1 .
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Pushing into Registry
        run: |
         docker images 
         docker push haseeb77777/github:latest

      
 

