name: Build and Cache Docker Image

on:
  push:
    branches:
      - master
############################################################################################################################################
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Docker layers
        id: cache
        uses: satackey/action-docker-layer-caching@v0.0.11
        with:
          key: docker-cache-${{ github.sha }}
          restore-keys: |
            docker-cache-

      - name: Check if cache hit
        id: cache-hit
        run: |
          echo ::set-output name=hit::$(if [ -z "${{ steps.cache.outputs.cache-hit }}" ]; then echo false; else echo true; fi)

      - name: Load Docker image from cache
        if: steps.cache-hit.outputs.hit == 'true'
        run: |
          docker load -i cache.tar

      - name: Build and tag Docker image
        run: |
          docker build -t tkxel:${{ github.sha }} .

      - name: Save Docker image to cache
        run: |
          docker save -o cache.tar tkxel:${{ github.sha }}

          

 

      
 

